version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8111
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8111:8111
    env_file:
      - ./.env.dev
