# Generated by Django 2.2.1 on 2019-05-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ip_addr', models.GenericIPAddressField()),
                ('http_method', models.CharField(max_length=10)),
                ('request_uri', models.URLField()),
                ('error_code', models.PositiveSmallIntegerField()),
                ('response_size', models.SmallIntegerField()),
            ],
        ),
    ]
